import { Flex, Box, Button, Spacer, useColorMode } from '@chakra-ui/react';
import { MdDarkMode, MdLightMode } from 'react-icons/md';
import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
// import styles from '../styles/Home.module.css';

export default function Home({ respone }) {
  const { colorMode, toggleColorMode } = useColorMode();

  const baseUrl = 'https://burgers1.p.rapidapi.com/burgers';

  // const fetchApi = async (url) => {
  //   const { data } = axios.get(url, {
  //     headers: {
  //       'x-rapidapi-host': 'burgers1.p.rapidapi.com',
  //       'x-rapidapi-key': '7d05c35a5dmsh62d22859cec4f8ep14dd4fjsnb5e90985873a',
  //     },
  //   });

  //   return data;
  // };

  console.log(respone);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>
        <Spacer />
        <Box p="5" fontSize={22} cursor="pointer" onClick={toggleColorMode}>
          {colorMode === 'light' ? <MdDarkMode /> : <MdLightMode />}
        </Box>
      </Flex>
    </>
  );
}

export async function getStaticProps() {
  const options = {
    method: 'GET',
    url: 'https://burgers1.p.rapidapi.com/burgers',
    headers: {
      'x-rapidapi-host': 'burgers1.p.rapidapi.com',
      'x-rapidapi-key': '7d05c35a5dmsh62d22859cec4f8ep14dd4fjsnb5e90985873a',
    },
  };
  const { data } = await axios.request(options);

  return {
    props: {
      respone: data,
    },
  };
}
